import { precacheAndRoute, cleanupOutdatedCaches, createHandlerBoundToURL } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';
import { registerRoute, NavigationRoute } from 'workbox-routing';

self.skipWaiting();
clientsClaim();
cleanupOutdatedCaches();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Listen for notification clicks
self.addEventListener('notificationclick', (event) => {

    event.notification.close();

    // The visit ID passed when the notification was scheduled
    const visitId = event.notification.data?.visitId;

    // Try to find an open window of the app and focus it
    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
            let matchingClient = null;

            // Look for a matching client (an open tab of our app)
            for (const client of windowClients) {
                if (client.url.includes(self.registration.scope) && 'focus' in client) {
                    matchingClient = client;
                    break;
                }
            }

            if (matchingClient) {
                // App is already open, just focus it and send a message to trigger the visual alarm
                return matchingClient.focus().then(() => {
                    matchingClient.postMessage({ type: 'ALARM_CLICKED', visitId });
                });
            } else {
                // App is not open, open a new window
                return clients.openWindow(self.registration.scope).then((client) => {
                    // Send a message after a short delay to allow the app to initialize
                    if (client) {
                        setTimeout(() => {
                            client.postMessage({ type: 'ALARM_CLICKED', visitId });
                        }, 2000);
                    }
                });
            }
        })
    );
});

// Also listen for pushes if we ever add a backend
self.addEventListener('push', (event) => {
    if (event.data) {
        const data = event.data.json();
        event.waitUntil(
            self.registration.showNotification(data.title || 'Reminder', {
                body: data.body,
                icon: '/pwa-192x192.png',
                data: data.data,
                requireInteraction: true,
            })
        );
    }
});
