import { precacheAndRoute, cleanupOutdatedCaches, createHandlerBoundToURL } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';
import { registerRoute, NavigationRoute } from 'workbox-routing';

self.skipWaiting();
clientsClaim();
cleanupOutdatedCaches();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

let upcomingAlarms = [];
let notifiedVisits = new Set();

// Listen for messages from the app to update the alarm list
self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SYNC_VISITS') {
        upcomingAlarms = event.data.visits;
        console.log('SW: Alarms Synced', upcomingAlarms.length);
        // Clean up notifiedVisits that are no longer in the list or are completed
        const currentIds = new Set(upcomingAlarms.map(v => v.id));
        for (const id of notifiedVisits) {
            if (!currentIds.has(id)) notifiedVisits.delete(id);
        }
    }
});

// Periodic Alarm Checker (Runs every minute in the background)
setInterval(() => {
    const now = new Date();
    const year = now.getFullYear();
    const month = String(now.getMonth() + 1).padStart(2, '0');
    const day = String(now.getDate()).padStart(2, '0');
    const today = `${year}-${month}-${day}`;
    
    upcomingAlarms.forEach(visit => {
        if (visit.date === today && visit.status === 'pending' && !notifiedVisits.has(visit.id)) {
            const [h, m] = visit.time.split(':').map(Number);
            const visitTime = new Date();
            visitTime.setHours(h, m, 0, 0);
            
            const diff = (visitTime - now) / (1000 * 60);
            const leadTime = visit.reminderMinutes || 60;

            if (diff > 0 && diff <= leadTime) {
                notifiedVisits.add(visit.id);
                self.registration.showNotification(`🚨 NOTIFY: ${visit.customerName}`, {
                    body: `URGENT: Meeting at ${visit.time} in ${visit.location}!`,
                    icon: '/pwa-192x192.png',
                    badge: '/pwa-192x192.png',
                    tag: `alarm-${visit.id}`,
                    renotify: true,
                    requireInteraction: true,
                    vibrate: [1000, 500, 1000, 500, 1000, 500],
                    data: { visitId: visit.id },
                    actions: [
                        { action: 'view', title: 'Start Alarm Voice', icon: '📢' },
                        { action: 'dismiss', title: 'Got it', icon: '✅' }
                    ]
                });
            }
        }
    });
}, 60000); // Check every minute

// Listen for notification clicks
self.addEventListener('notificationclick', (event) => {
    event.notification.close();
    const visitId = event.notification.data?.visitId;

    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
            let matchingClient = null;
            for (const client of windowClients) {
                if (client.url.includes(self.registration.scope) && 'focus' in client) {
                    matchingClient = client;
                    break;
                }
            }

            if (matchingClient) {
                return matchingClient.focus().then(() => {
                    matchingClient.postMessage({ type: 'ALARM_CLICKED', visitId });
                });
            } else {
                return clients.openWindow(self.registration.scope).then((client) => {
                    if (client) {
                        setTimeout(() => {
                            client.postMessage({ type: 'ALARM_CLICKED', visitId });
                        }, 3000);
                    }
                });
            }
        })
    );
});
